import {
  ExclamationTriangleIcon as ErrorIconMini,
  CheckCircleIcon as CheckCircleIconMini,
  EyeIcon as EyeIconMini,
  EyeSlashIcon as EyeSlashIconMini,
  ChevronLeftIcon as ChevronLeftIconMini,
  ArrowUpTrayIcon as ArrowUpTrayIconMini,
  XMarkIcon as XMarkIconMini,
  InformationCircleIcon as InformationCircleIconMini,
  CheckIcon as CheckIconMini,
  HomeIcon as HomeIconMini,
  QuestionMarkCircleIcon as QuestionMarkCircleIconMini,
  ArrowDownTrayIcon as ArrowDownTrayIconMini,
  PlusIcon as PlusIconMini,
  Cog8ToothIcon as Cog8ToothIconMini,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleIconMini,
  ChevronRightIcon as ChevronRightIconMini,
  ChevronDownIcon as ChevronDownIconMini,
} from "@heroicons/react/20/solid";
import {
  InformationCircleIcon,
  HomeIcon as HomeIconOutline,
  QuestionMarkCircleIcon as QuestionMarkCircleIconOutline,
  ChevronLeftIcon as LeftArrowIcon,
} from "@heroicons/react/24/outline";

export {
  ChevronDownIconMini,
  ChevronRightIconMini,
  ErrorIconMini,
  CheckCircleIconMini,
  EyeIconMini,
  EyeSlashIconMini,
  ChevronLeftIconMini,
  ArrowUpTrayIconMini,
  XMarkIconMini,
  InformationCircleIconMini,
  InformationCircleIcon,
  CheckIconMini,
  HomeIconMini,
  HomeIconOutline,
  QuestionMarkCircleIconOutline,
  ArrowDownTrayIconMini,
  PlusIconMini,
  Cog8ToothIconMini,
  ArrowRightOnRectangleIconMini,
  LeftArrowIcon,
};
